name: Unit Tests
on:
  pull_request:
    paths:
    - '.github/**'
    - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: printf '%s\n' 'y' 'y' | sh <(curl -s https://smartpy.io/cli/install.sh)
      - run: ~/smartpy-cli/SmartPy.sh test smart-py/objkt_swap.py /dev/null
      - run: ~/smartpy-cli/SmartPy.sh test smart-py/marketplace.py /dev/null
      - run: ~/smartpy-cli/SmartPy.sh test smart-py/fa2.py /dev/null
  compile:
    needs: [test]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - run: printf '%s\n' 'y' 'y' | sh <(curl -s https://smartpy.io/cli/install.sh)
      - run: ~/smartpy-cli/SmartPy.sh compile smart-py/objkt_swap.py /tmp/objkt_swap
      - run: ~/smartpy-cli/SmartPy.sh compile smart-py/marketplace.py /tmp/marketplace
      - run: ~/smartpy-cli/SmartPy.sh compile smart-py/fa2.py /tmp/fa1
      - run: ~/smartpy-cli/SmartPy.sh compile smart-py/proxy.py /tmp/proxy
